
name: smart_voice_writer_pro
description: Provati Digital Smart Voice Writer PRO
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^6.5.1
  permission_handler: ^11.3.0
  google_generative_ai: ^0.4.4
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
flutter:
  uses-material-design: true
